export enum AvailableConfigs {
  APP_PORT = 'APP_PORT',
  DATABASE_URI = 'DATABASE_URI',
  JWT_SECRET = 'JWT_SECRET',
  API_KEY = 'API_KEY',
  SEND_GRID_KEY = 'SEND_GRID_KEY',
  FROM_EMAIL = 'FROM_EMAIL',
  TWILIO_ACC_SID = 'TWILIO_ACC_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_PHONE_NUMBER = 'TWILIO_PHONE_NUMBER',
}
